[files]
extend-exclude = [
    "_oak_mods/",
    "_oak2_mods/",
    "_willow1_mods/",
    "_willow2_mods/",
]

[default.extend-words]
# this is just a normal word it doesn't recognise?
moreso = "moreso"
